# Generated by Django 3.2.18 on 2023-05-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='label',
        ),
    ]
