# Generated by Django 3.2.18 on 2023-05-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='creation_date',
            new_name='added_on',
        ),
    ]
