# Generated by Django 3.2.18 on 2023-05-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_remove_wishlist_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='added_on',
            new_name='date',
        ),
    ]
