# Generated by Django 3.2.18 on 2023-05-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_alter_wishlistitem_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
