# Generated by Django 3.2.18 on 2023-05-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_alter_wishlistitem_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
