# Generated by Django 3.2.18 on 2023-05-11 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_rename_user_profile_wishlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='item',
        ),
    ]
