# Generated by Django 3.2.18 on 2023-05-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_auto_20230512_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='profile',
            new_name='user',
        ),
    ]
