# Generated by Django 3.2.18 on 2023-05-11 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_rename_product_wishlist_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='item',
            new_name='product',
        ),
    ]
