# Generated by Django 3.2.18 on 2023-05-12 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0008_alter_wishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_wishlist', to='wishlist.wishlist'),
        ),
    ]
