# Generated by Django 3.2.18 on 2023-05-21 15:03

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_remove_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now, validators=[events.models.validate_date])),
                ('time', models.TimeField(default='12:00')),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('street_address', models.CharField(blank=True, max_length=80, null=True)),
                ('town_or_city', models.CharField(max_length=40)),
                ('postcode', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Please use numbers and letters only.')])),
                ('products', models.ManyToManyField(blank=True, to='products.Product')),
            ],
            options={
                'unique_together': {('name', 'date', 'time', 'location', 'town_or_city')},
            },
        ),
    ]
