# Generated by Django 3.2.18 on 2023-05-20 22:13

from django.db import migrations, models
import django.utils.timezone
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, validators=[events.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default='12:00'),
        ),
    ]
