# Generated by Django 3.2.18 on 2023-05-15 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_auto_20230505_1603'),
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouritesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_user', to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FavouritesListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_list', to='favourites.favouriteslist')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_products', to='products.product')),
            ],
        ),
    ]
