# Generated by Django 3.2.18 on 2023-05-15 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
        ('profiles', '0002_auto_20230505_1603'),
        ('favourites', '0002_alter_favouriteslistitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteslist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='favouriteslistitem',
            name='favourites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favourites.favouriteslist'),
        ),
        migrations.AlterField(
            model_name='favouriteslistitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
