# Generated by Django 3.2.18 on 2023-05-18 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_remove_product_rating'),
        ('favourites', '0003_auto_20230515_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='products.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='favouriteslistitem',
            name='favourites',
        ),
        migrations.RemoveField(
            model_name='favouriteslistitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='FavouritesList',
        ),
        migrations.DeleteModel(
            name='FavouritesListItem',
        ),
    ]
