# Generated by Django 3.2.18 on 2023-05-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0004_auto_20230518_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourites',
            options={'verbose_name_plural': 'Favourites'},
        ),
    ]
