# Generated by Django 3.2.18 on 2023-05-21 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Please enter a valid UK postcode. Numbers and letters only.')]),
        ),
    ]
