# Generated by Django 3.2.18 on 2023-05-16 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coffee_qty_g', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('grind_size', models.CharField(choices=[('Extra-Coarse', 'Extra-Coarse'), ('Coarse', 'Coarse'), ('Medium', 'Medium'), ('Medium-Fine', 'Medium-Fine'), ('Fine', 'Fine'), ('Superfine', 'Superfine')], default='Medium', max_length=20)),
                ('water_temp_c', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('water_volume_ml', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)])),
                ('brew_time_mins', models.DecimalField(decimal_places=2, max_digits=4)),
                ('method', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
            options={
                'verbose_name_plural': 'Recipes',
            },
        ),
    ]
