# Generated by Django 3.2.18 on 2023-05-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
